### PR TITLE
Add http retries to upgrade_all_service_instances errand

### PR DESCRIPTION
**Pull request by aemengo**
Upgrade github.com/craigfurman/herottp to code referenced here:
  https://github.com/craigfurman/herottp/pull/1
  sha: 4ec2babe9741d729563e1894628af2a2c2d96b29

we occasionally see our errand fail mid-run due to timeout issues. This might help alleviate the problem, though it has no exponential backoff implemented

screen shot 2018-01-12 at 4 00 06 pm

### CODE REVIEW

**Comment by avade** [comment]
Feedback from the team is that we would like to wait until the Herottp PR has been merged so that we can vendor off of master.

**Comment by avade** [comment]
The Herottp PR has been merged. Can you update this PR to vendor that version @aemengo.

**Comment by aemengo** [comment]
@avade updated, sir. 🔥

**Comment by servicesenablement** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by servicesenablement** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by servicesenablement** [comment]
To view the CI pipeline for this PR, see https://wings.concourse.ci/teams/services-enablement/pipelines/odb-pull-request

**Comment by kirederik** [comment]
Thanks!

**Pull request merged**
